

###


POST http://localhost:3000/content HTTP/1.1
Content-Type: application/json

{
    "title" :"GameOfThrones", 
    "hashtag" :"#got", 
    "description" :"web series", 
    "video_link" :"content/videos/got.mp4", 
    "video_running_time" :30,
    "region_availablity" : "India",
    "language":"english"


}

###

### 
GET http://localhost:3000/content HTTP/1.1


### 
GET http://localhost:3000/content/language/english HTTP/1.1